# Generated by Django 4.0.3 on 2022-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('TodoItemId', models.AutoField(primary_key=True, serialize=False)),
                ('TodoTitle', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=500)),
                ('CreatedDate', models.DateField()),
                ('IsComplete', models.BooleanField()),
            ],
        ),
    ]
